### ISSUE TITLE
List of thing to completed for new update

### ISSUE THREAD

**Issue by NubeDev** [NubeIO/bonescript-dashboard#100]
## Sensor-List
![image](https://user-images.githubusercontent.com/18637436/56318336-5038b280-61a2-11e9-9824-eb4fc406b6d9.png)

## Graph 24Hr time format
![image](https://user-images.githubusercontent.com/18637436/56318697-0b614b80-61a3-11e9-9897-9a02aa404ccb.png)

## issue with units when editing point on °C
![image](https://user-images.githubusercontent.com/18637436/56318796-48c5d900-61a3-11e9-9c22-4035d4cef898.png)

## History setting 
https://ant.design/components/input-number/

![image](https://user-images.githubusercontent.com/18637436/56319190-53cd3900-61a4-11e9-8b21-ce84bb49743d.png)

# Chart Issue calling last x

![image](https://user-images.githubusercontent.com/18637436/56322628-ee317a80-61ac-11e9-9869-89a01746575c.png)

## Display history name and not key
![image](https://user-images.githubusercontent.com/18637436/56322660-07d2c200-61ad-11e9-857e-5bfbb1128df9.png)

## Node-red iframe issue

![image](https://user-images.githubusercontent.com/18637436/56323117-3b621c00-61ae-11e9-910c-70118fe9925b.png)

## Adding schedule events 
![image](https://user-images.githubusercontent.com/18637436/56323161-5fbdf880-61ae-11e9-982d-cd03e631f75f.png)
**

**Comment by jrh21** [comment]
Are you able to update on the Node-red iframe issue @riteshakya037 .
Thanks

**Comment by riteshakya037** [comment]
@RaiBnod Last I was aware you were working on this Node-red iframe issue right?

**Comment by RaiBnod** [comment]
Yeah, but that fixes was on `feature/installer-page`, which takes time to merge on our ongoing development. So, creating just a new pull request to just address that NodeRED fix (showing it on full screen).
