### ISSUE TITLE
API Dashboard | CSV Formatting

### ISSUE THREAD

**Issue by riteshakya037** [NubeIO/bonescript-dashboard#109]
Edge controller - 
URL: cbaiot00091.ddns.net
Password: 2e70f98f0e59

* Export via dashboard:
![image](https://user-images.githubusercontent.com/42997992/57991697-ef2f3200-7af3-11e9-8be7-021da63e0ac7.png)
* CSV Export:
![image](https://user-images.githubusercontent.com/42997992/57991762-3e756280-7af4-11e9-8a88-6f49d3cb56b8.png)
* Delete UI points:
![image](https://user-images.githubusercontent.com/42997992/57991811-81373a80-7af4-11e9-8d9d-d5bbeace6850.png)
* Batch Add:
![image](https://user-images.githubusercontent.com/42997992/57991849-bba0d780-7af4-11e9-9983-9b7cc19942c8.png)
* Re export CSV note formatting is different have also added UI points back to API and formatting does not resume to original format:
![image](https://user-images.githubusercontent.com/42997992/57991888-f571de00-7af4-11e9-8cbf-c45298f6e187.png)

**Comment by NubeDev** [comment]
This is using the current version of bonescript api

**Comment by jrh21** [comment]
There are missing fields from the CSV export:

* Latest export 
![image](https://user-images.githubusercontent.com/42997992/58052035-1e4aaf80-7b97-11e9-8c85-d988cdeefae3.png)
* All fields required
![image](https://user-images.githubusercontent.com/42997992/58052086-42a68c00-7b97-11e9-8e78-544c0f67ece5.png)

**Comment by riteshakya037** [comment]
@jrh21 Could you confirm with the new update I just pushed.
