### ISSUE TITLE
User login root

### ISSUE THREAD

**Issue by NubeDev** [NubeIO/bonescript-dashboard#110]
When logging into the bs-api dashboard it always loads the default user `root`

This is kinda annoying as when you enter something wrong like a password you to reenter the username again

**Comment by RaiBnod** [comment]
@riteshakya037  I think this one is already fixed in `https://github.com/NubeIO/bonescript-dashboard/pull/107`. Please confirm.

**Comment by riteshakya037** [comment]
@NubeDev I'm not a hundred percent sure I understand what you mean. Assuming you are talking about the prefilled username/password, its probably from .env in the server. We'll make sure to get that sorted.
